### ISSUE TITLE
Resolving Missing ShortId in the Database

### ISSUE THREAD

**Issue by Abh-I-seK** [abhijeetnishal/URLShortener#109]
**Describe the bug**
After shortening a URL, we get an URL in form of https://urlsrt.vercel.app/data. 
Now if we pass a arbitrary value in place of <b>data </b>then it shows the following.
In the example below, I used the URL : https://urlsrt.vercel.app/111222

![image](https://github.com/abhijeetnishal/URLShortener/assets/134422863/c4bac916-2bf2-46a9-8d91-a4604d1f9ecc)

So, I think if in getSpecificUrl() (in server/controller/urls.js) 
once we find the data based on shortId then check if its null. If null, then we will redirect the user to an 404 page which will say that 
"This link does not exist".

And will also add link to navbar, which will redirect to homepage.

Could you please assign this issue to me under GSSOC 24.

**To Reproduce**
1. Go to https://urlsrt.vercel.app/111222

**Expected behavior**
The above screenshot.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Arc
 - Version: 1.2.1 (29300)

**Comment by abhijeetnishal** [comment]
Great, Assigning this issue to you now.

You are implementing frontend and backend both rigth?
The UI should be responsive also right?

**Comment by Abh-I-seK** [comment]
> Great, Assigning this issue to you now.
> 
> You are implementing frontend and backend both right? The UI should be responsive also right?

Yes, I will implement both responsive frontend and backend.
