### ISSUE TITLE
About the website

### ISSUE THREAD

**Issue by Shivani756** [abhijeetnishal/URLShortener#118]
**Is your feature request related to a problem? Please describe.**
It is to make the users aware of the need of this feature and where can you use this and also it's importance

**Describe the solution you'd like**

i'll be creating a about page kind of thing mentioning what our website does and why is it important in  the today's corporate world
![about](https://github.com/abhijeetnishal/URLShortener/assets/139329176/65d96300-c825-4372-b0db-3638d3c24dab)

**Comment by abhijeetnishal** [comment]
Hey, this feature will be added by issue #70 
Contribute to other issues, good luck.
