### ISSUE TITLE
Enhancing the UI of the application

### ISSUE THREAD

**Issue by devu007** [abhijeetnishal/URLShortener#119]
**Is your feature request related to a problem? Please describe.**
We can improve the UI of the application.

**Describe the solution you'd like**
We can improve it by adding some gradient and utilizing the react-icons library to enhance the input fields.

**Additional context**
Here is the sample of what I am thinking of:
<img width="1425" alt="image" src="https://github.com/abhijeetnishal/URLShortener/assets/101053111/d58d2c04-1e6f-44de-a5d9-65fbf52cde54">

Please review this Issue and suggest if any changes @abhijeetnishal

**Comment by abhijeetnishal** [comment]
Hey @devu007, there is an issue #70 for this
Contribute to other issues or project, good luck.
