### ISSUE TITLE
Adding Signup Signin buttons On the Navbar 

### ISSUE THREAD

**Issue by imkeertiag** [abhijeetnishal/URLShortener#121]
As there is Server in the code. But in the Client side there is no authentication of the User , no button for Signup and no Register Buttons are Seen.

![Screenshot 2024-05-24 234745](https://github.com/abhijeetnishal/URLShortener/assets/135499447/b0761337-1645-4ae8-be33-756d8d5054be)

**Comment by abhijeetnishal** [comment]
Hey @imkeertiag, this feature will be added by issue #70  
Contribute to other issues, good luck.
