### ISSUE TITLE
After the shortening one URL there is no option for shortening the another URL. So i think we have to add a button below oncliking which will empty the input box so user can add another url for shortening.

### ISSUE THREAD

**Issue by VinayLodhi1712** [abhijeetnishal/URLShortener#125]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I enter the one url and if I wanted another url to shortened I need to refresh the url or had to clear the input box by myself manually. That's not a good user experience.

**Describe the solution you'd like**
I want to add a button below onclicking which will empty the input box of url which is a good user experience option.

**Issue screenshot**
![tinyurl](https://github.com/abhijeetnishal/URLShortener/assets/135756009/8e193286-1f9a-4098-a653-8967b5887b7a)

**Comment by VinayLodhi1712** [comment]
@abhijeetnishal sir please assigned this issue under GSSOC'24.

**Comment by abhijeetnishal** [comment]
Hey @VinayLodhi1712, this feature will be added by issue #70
Contribute to other issues, good luck.
