### ISSUE TITLE
[Enhancement] Adding a Footer to a Webpage Enhances Usability and Aesthetic Appeal 

### ISSUE THREAD

**Issue by karishmaaa101** [abhijeetnishal/URLShortener#128]
**Is your feature request related to a problem? Please describe.**
Adding a footer to a webpage can indeed enhance its usability and aesthetic appeal. A footer typically provides important information and links that help users navigate the site more easily and access additional resources. 

- Contact Information: Provides users with ways to get in touch with the site owner or company, enhancing communication and customer service.

- Social Media Links: Helps users connect with the brand on various social platforms, increasing engagement and reach.

- Privacy Policy and Terms of Service: Ensures users have easy access to important legal documents, promoting transparency and trust.

- Sitemap: Offers a quick navigation tool for users to find specific pages, improving site usability.

- Newsletter Signup: Allows users to subscribe to updates, increasing user engagement and retention.

- Copyright Information: Protects the site's content legally and informs users about the ownership of the content.

- Navigation Links: Provides quick links to important sections of the site, improving the overall user experience.

**Describe the solution you'd like**
![image](https://github.com/abhijeetnishal/URLShortener/assets/104766763/dde37835-5bf2-4e0e-893e-0ee2715906d5)

![image](https://github.com/abhijeetnishal/URLShortener/assets/104766763/448ab0cb-8431-4fb7-9033-2ea9f010f714)

**Additional context**
I am Gssoc'2024 contributor, and I have followed all the guidelines.

**Comment by abhijeetnishal** [comment]
Hey @karishmaaa101, this issue #70 add this feature.
Contribute to other issues or projects good luck
