### ISSUE TITLE
Adding a FAQ section

### ISSUE THREAD

**Issue by AkshitGarg24** [abhijeetnishal/URLShortener#129]
A FAQ section should be made available to the website which enhances user experience by addressing common queries efficiently and reducing support burden. An image is attached as an example for the FAQ section.

![URL](https://github.com/abhijeetnishal/URLShortener/assets/153659573/dde9e690-1f29-4f66-a6b7-b40fb6a9d322)

**Comment by abhijeetnishal** [comment]
Hey @AkshitGarg24, this will be added in this issue #70 
Contribute to other issues or project, good luck.
