### ISSUE TITLE
[BUG] Issue with Theme Toggle on initial load

### ISSUE THREAD

**Issue by AMS003010** [abhijeetnishal/URLShortener#132]
**Describe the bug**
When a person visits the website for the first time, its in `dark` mode but the toggle is set to `light`.

**To Reproduce**
1. Go to [ShortURL](https://urlsrtner.vercel.app/)
2. Make sure that the local storage is cleared 
3. Reload
4. Notice that the toggle is in `light` even though it is in `dark` mode

**Expected behavior**
When the website is loaded, the initial theme is `dark` and the the Theme Toggle should also show `dark` 

**Screenshots**
When the website is initially visited for the first time a user 👇
![image](https://github.com/abhijeetnishal/URLShortener/assets/111883236/47592cb9-0dfc-4b44-97a3-f1b4f7b94dfe)

It should look like this 👇
![image](https://github.com/abhijeetnishal/URLShortener/assets/111883236/4be9c11e-6587-44d2-9489-333775b49d6f)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version 125.0.6422.113 (Official Build) (64-bit)

**Additional context**
This problem can be solved by the setting the `theme` state to `dark` as the component mounts. Please do assign me this issue under GSSOC'24

**Comment by abhijeetnishal** [comment]
Hey @AMS003010, how do you planning to solve this bug. Could you explain your appraoch?

**Comment by AMS003010** [comment]
The `Theme Toggle` feature is working properly, the only issue is the initial value of the `Theme` state not being set to `dark` when the component loads (since `dark` is the default theme). I propose to set the initial value of  `Theme` to `dark` using a `useEffect` hook as the component loads.

**Comment by abhijeetnishal** [comment]
Yes, correct. Don't set the theme to dark make the theme as system one and according to that set the toggle.
The reason is I am not trying to use useEffect because it will make component client Instead of server.

**Comment by abhijeetnishal** [comment]
Hey @Srikar04, this issue is already assigned to @AMS003010. This is small issue doesn't require 2 contributers. Contribute to other issues good luck

**Comment by AMS003010** [comment]
@abhijeetnishal  I have made the PR with the required changes, please do review it.

**Comment by abhijeetnishal** [comment]
Closing this issue as completed.
