### ISSUE TITLE
[BUG] Validation of URLs Fails for Certain Status Codes

### ISSUE THREAD

**Issue by Srikar04** [abhijeetnishal/URLShortener#137]
Bug Description:
The URL validation logic in our project currently only considers a URL to be valid if it returns a 200 OK status code. However, some valid URLs, such as LinkedIn's homepage, return other status codes like 999, which causes our validation to incorrectly mark them as invalid. This issue affects the accuracy and reliability of the URL validation feature.

Steps to Reproduce:

Use the current URL validation logic to validate https://www.linkedin.com/in/srikarmellachervu/
Observe that the validation fails due to the status code 999 returned by LinkedIn.
Expected Behavior:
The URL validation should account for valid status codes other than 200 OK, including but not limited to 301 Moved Permanently, 302 Found, and specific custom status codes like LinkedIn's 999.

Actual Behavior:
The URL validation fails for valid URLs that return status codes other than 200 OK which gives an output "Invalid URL"

![1](https://github.com/abhijeetnishal/URLShortener/assets/101891231/fadd54b9-6056-4f07-bc6a-4ea8ff4cf1cb)

![2](https://github.com/abhijeetnishal/URLShortener/assets/101891231/e9e83bca-9d11-4948-b464-cceeb9a1c341)

Possible Solution:
Update the validation logic to handle a broader range of valid HTTP status codes, such as 301 Moved Permanently, 302 Found, etc.
Implement handling for specific known custom status codes, like LinkedIn's 999.
Consider implementing a retry mechanism for temporary issues or status codes indicating the need for a second attempt.

Please issue this to come under gssoc 24

 - OS: Linux
 - Browser Brave

**Comment by abhijeetnishal** [comment]
Thanks for pointing it you this issue.
Hey @RoshanAnsy, look into this issue.

**Comment by Srikar04** [comment]
I have a working solution to this please assign this to me so I can create a pull request

**Comment by abhijeetnishal** [comment]
Hey @Srikar04, could you explain your approach. If this is the case then we can't add every response code for every website in our code.

**Comment by abhijeetnishal** [comment]
This is fine but are you sure it will work for all have you tested it because in later time what if someone else reports that some links are not working. Although I am assigning this issue to you.

Hey @RoshanAnsy, i think we missed these cases.

**Comment by abhijeetnishal** [comment]
Closing this issue as done.
