### ISSUE TITLE
Shorten URL's starting with "www"

### ISSUE THREAD

**Issue by avayyyyyyy** [abhijeetnishal/URLShortener#140]
**Describe the bug**
while entering the correct "www" URL, still getting that enter a valid URL.

**Expected behavior**
It should also shortlist the URL's starting with "www.google.com"

**Screenshots**
<img width="1792" alt="Screenshot 2024-05-30 at 7 55 35 PM" src="https://github.com/abhijeetnishal/URLShortener/assets/111121419/a684f265-6d97-43ee-902e-5525c9de01a9">

**Additional context**
Please assign this issue to me.

**Comment by abhijeetnishal** [comment]
It should not work until it's https/http is there as URL contains this. 

Contribute to other issues, good luck.

**Comment by avayyyyyyy** [comment]
it can work using regex

**Comment by abhijeetnishal** [comment]
Hey I think people rarely type URL www.... They will just copy and paste it that's why I think it's fine.
