### ISSUE TITLE
Make the UI Responsive

### ISSUE THREAD

**Issue by jashanp2005** [abhijeetnishal/URLShortener#151]
The user interface of the project is not responsive for all types of devices. Kindly assign me this issue so that I can make the user interface responsive.
![Screenshot 2024-06-01 153003](https://github.com/abhijeetnishal/URLShortener/assets/160238258/79cd5e7d-48aa-4084-944a-c54699f6a748)

**Comment by abhijeetnishal** [comment]
Hey @jashanp2005, it's response you are checking for less than 320 viewpoint that's why.

Contribute to other issues good luck.
