### ISSUE TITLE
adding a preloader to website

### ISSUE THREAD

**Issue by dhairyagothi** [abhijeetnishal/URLShortener#152]
i can add a preloaderr to website please assign me this task under gssoc

**Comment by riyasaxena32** [comment]
I am interested in resolving issue for GSSoC '24 and believe my skills in make me a good fit. Please assign it to me.

**Comment by abhijeetnishal** [comment]
Hey @dhairyagothi, we are currently redesigning the UI so currently it's not required.

Contribute to other issues, good luck.
