### ISSUE TITLE
Adding SignUp and Login features to the website

### ISSUE THREAD

**Issue by atharvarekhawar** [abhijeetnishal/URLShortener#157]
**Is your feature request related to a problem? Please describe.**
Currently thee is no way to track all the url's generated by the user and their authentication .

**Describe the solution you'd like**
The server routes are already coded for authentication with middleware which I have closely followed up during solving previous issues so c thonnecting those routes with frontend will be easy task .

I will also implement good looking sign up and login pages with proper functionality .

**Describe alternatives you've considered**

**Additional context**
I would like to contribute to this issue under GSSOC'24 and after this implementation I can also code frontend for displaying all the url's of the user once the authentication is completed and this will be easy for me as I already have coded server controller's for it.

**Comment by atharvarekhawar** [comment]
@abhijeetnishal plz assign this issue to me.

**Comment by atharvarekhawar** [comment]
@abhijeetnishal we can also start making page to display all url's created by the user once authentication part is done and then add analytics to it.

**Comment by abhijeetnishal** [comment]
Hey @atharvarekhawar, login/signup are already there go to /auth/login you will see.

Closing this issue as duplicate.

**Comment by atharvarekhawar** [comment]
@abhijeetnishal but there is no registration and login feature on frontend

**Comment by atharvarekhawar** [comment]
The homepage do not have the needed buttons

**Comment by abhijeetnishal** [comment]
Hey @atharvarekhawar, as I mentioned these issues will be fixed as there is still delay by the contributor.
