### ISSUE TITLE
Contact form for the website

### ISSUE THREAD

**Issue by atharvarekhawar** [abhijeetnishal/URLShortener#158]
**Is your feature request related to a problem? Please describe.**
If a user want's to reach out to the project maker then he/she would;d either have to connect on social or dicord.

**Describe the solution you'd like**
What if a contact page is created and user can query then and there through the form to the project owner about the website.

**Describe alternatives you've considered**

**Additional context**
I would like to contribute to this issue and create a contact form page through which user can send mail's to project admin.

**Comment by atharvarekhawar** [comment]
@abhijeetnishal plz assign this issue to me

**Comment by abhijeetnishal** [comment]
This issue will be fixed by #70 

Contribute to other issues good luck.
