### ISSUE TITLE
Improving the font-family used in website

### ISSUE THREAD

**Issue by Khushipawar37** [abhijeetnishal/URLShortener#159]
The font used in a website is the first thing noticed by users, sometimes they even get attracted by the amazing UI design along with catchy fonts used. Hence I would like to update the font-family and give it a amore elegant and better look.

**Comment by riyasaxena32** [comment]
I am interested in resolving issue for GSSoC '24 and believe my skills in make me a good fit. Please assign it to me.

**Comment by abhijeetnishal** [comment]
Hey @riyasaxena32, the font family is fine for now. 

Contribute to other issues good luck.
