### ISSUE TITLE
[Feature] Implement Login/Signup with JWT Authentication (Server side)

### ISSUE THREAD

**Issue by abhijeetnishal** [abhijeetnishal/URLShortener#16]
## Description:
The current URL Shortener project lacks a user authentication mechanism, which prevents users from saving and managing their shortened URLs. To address this, we need to implement a login/signup system with JWT (JSON Web Token) authentication on the server-side. This will enable users to create an account, log in, and save their shortened URLs for future reference.

## Requirements:
1. User Registration:
    - Create a registration endpoint (v1/auth/signup) that accepts a username, email, and password.
    - Validate user input and store the user data in the MongoDB database.

2. User Login:
    - Create a login endpoint (v1/auth/login) that accepts a username (or email) and password.
    - Verify the user credentials against the stored data in the MongoDB database.
    - Generate a JWT token upon successful login, which will be used for authentication.

3. JWT Authentication:
    - Implement JWT token generation and verification using a library like jsonwebtoken.
    - Store the JWT token in the user's browser storage (e.g., localStorage).
    - Verify the JWT token on each request to protected endpoints.

4. Error Handling:
    - Handle errors and exceptions properly, including invalid login credentials, expired tokens, and database errors, etc.
  
## Technical Details:
- The project uses Node.js (Express) as the backend framework and MongoDB as the database.
- The JWT token should be generated with a secret key stored as an environment variable.
- The user data should be stored in a users collection in the MongoDB database.

### Acceptance Criteria:
- A user can register with a unique username, email, and password.
- A user can log in with their credentials and receive a valid JWT token.
- The JWT token is verified on each request to protected endpoints.
- Error handling is implemented correctly for invalid login credentials, expired tokens, and database errors, etc.

### Estimated Time: 
This issue is estimated to take around 2-3 days to complete, depending on the contributor's experience.

**Comment by Mr-mahato** [comment]
I'm interested in working on the open issue regarding the implementation of user authentication within the URL Shortener project. I have experience with Node.js, Express, MongoDB, and JWT token handling, which aligns well with the project's requirements.

I've reviewed the issue's description and requirements and feel confident that I can deliver a robust and secure authentication solution. I understand the need for proper error handling and am ready to address those aspects.

Would you be open to assigning this issue to me? I'm eager to contribute to the project and believe I have the skills necessary to complete this task within the estimated timeframe.

**Comment by abhijeetnishal** [comment]
Hey @Mr-mahato, I am assigning this issue to you.
Best of luck.

**Comment by Ansh101112** [comment]
Hello @abhijeetnishal I am also interested in solving this issue could you assign me this issue?

**Comment by abhijeetnishal** [comment]
Hey @Ansh101112, this issue is already assigned, you can contribute to other issues.

**Comment by Mr-mahato** [comment]
@abhijeetnishal Thanks for giving me this issue , would you please don't mind me asking you a question . ie: should i start working on this issue or i have to work after 10th of may and then submit my pr.

**Comment by abhijeetnishal** [comment]
Hey @Mr-mahato, you can start working on this issue and because this issue will take take time to finish and from tomorrow program is live and once done you can create a PR.

**Comment by Mr-mahato** [comment]
@abhijeetnishal I have seen that there is one issue in this project where i we have to change the plain css to tailwind css , will it be okay if i am using the tailwind css for this issue which i am assign for.

**Comment by abhijeetnishal** [comment]
> Hey!! Assign this issue to me i want to work on this?

Hey @surendar-05, this issue is already assigned to @Mr-mahato. 
You can work on other issues, Good luck.

**Comment by abhijeetnishal** [comment]
> @abhijeetnishal I have seen that there is one issue #15 in this project where its mention to change the plain css to tailwind , will it be okay if i am using the tailwind css for this issue which i am assign for.

Hey @Mr-mahato, this issue is for server side only you don't need to worry about, there is another issue for client side.

**Comment by Sahilll15** [comment]
@abhijeetnishal assign the client side integration work to me

**Comment by abhijeetnishal** [comment]
Hey @Mr-mahato, don't do force update on PR, if i will merge it to master branch it will changes the original code with our code, also you didn't pull the code from master as i mentioned. I have fixed the changes of master branch. But remember all these things for future references. Good luck

I am closing this issue as completed.

**Comment by Mr-mahato** [comment]
![Screenshot from 2024-05-12 22-34-39](https://github.com/abhijeetnishal/URLShortener/assets/96912116/727ad7ba-8e96-43eb-a04c-fbd900a6e20b)
when i was trying to merge i was getting this error how to solve this one to merge with the master branch

**Comment by abhijeetnishal** [comment]
> ![Screenshot from 2024-05-12 22-34-39](https://private-user-images.githubusercontent.com/96912116/329867392-727ad7ba-8e96-43eb-a04c-fbd900a6e20b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU1MzU5OTcsIm5iZiI6MTcxNTUzNTY5NywicGF0aCI6Ii85NjkxMjExNi8zMjk4NjczOTItNzI3YWQ3YmEtOGU5Ni00M2ViLWEwNGMtZmJkOTAwYTZlMjBiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEyVDE3NDEzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRjZDhlYjk3NjQ4Mzc1ZDA0YWZmZWQ3MTdjNWMwYWE5YmU2ZjdiNTEzMGQ4ZGNkZTc4Y2VmMjVmNjUxNDQxNDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qtXC9kM8cVgnaHR8DNigwzPw6x4JdjkQOYTXhFYKgTs) when i was trying to merge i was getting this error how to solve this one to merge with the master branch

This is merged conflict which happens when you change the same code from two branches, it's need to fix before merging either you can accept the incoming change or current change after this the conflict get resolved.

But with force update it update the current not the upcoming which is from master branch.

**Comment by Mr-mahato** [comment]
Thanks i have learn it how to solve this merging issue , onwards i will merge my branch and keep it uptodate then only make some changes and then create a PR.

**Comment by abhijeetnishal** [comment]
> Thanks i have learn it how to solve this merging issue , onwards i will merge my branch and keep it uptodate then only make some changes and then create a PR.

Great 👏

**Comment by Mr-mahato** [comment]
I have also created the client side login and signup page if you allow me then i can contribute to that also.

**Comment by abhijeetnishal** [comment]
> I have also created the client side login and signup page if you allow me then i can contribute to that also.

Hey @Mr-mahato, one issue is already there I guess someone is already working on that.
