### ISSUE TITLE
[Bug] : Alerting Not Visible

### ISSUE THREAD

**Issue by sivaprasath2004** [abhijeetnishal/URLShortener#165]
**Describe the bug**
- In this project  copy icon click `copied` text doesn't visible.

**To Reproduce**
1. Go to project page.
2. Click on copy icon.
3. See error `copied` text

**Expected behavior**
- The text color will be change to `black` or other..

**Screenshots**

[Screencast from 2024-06-04 20-05-49.webm](https://github.com/abhijeetnishal/URLShortener/assets/121082414/5589b657-f5ee-43c3-8b93-7224e9282d71)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser: chrome

**Smartphone (please complete the following information):**
 - Device:Realme 8
 - OS: Android 12
 - Browser: chrome

**Comment by abhijeetnishal** [comment]
Hey @sivaprasath2004, there is an issue #70 for UI redesign that will fix this.

**Comment by sivaprasath2004** [comment]
@abhijeetnishal,sure
