### ISSUE TITLE
adding contact us page both backend and frontend functionality

### ISSUE THREAD

**Issue by Isha1233** [abhijeetnishal/URLShortener#167]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Isha1233** [comment]
@abhijeetnishal kindly assign this issue to me

**Comment by abhijeetnishal** [comment]
Hey @Isha1233, there is an issue #70 which is for redesigning the UI. How you are planning to implement this feature could you explain?

**Comment by Isha1233** [comment]
@abhijeetnishal I will add an icon of contact on clicking that a small box will open and where user can send mail to owner or will save its message on mongodb (I will use node js and mongodb for  backend ) . You can suggest I can implement any of them mail or saving to mongodb or both .

**Comment by abhijeetnishal** [comment]
Hey @Isha1233, do you have any design for the contact page. Also we don't need to save the message to DB. we just need to send an email from backend.

**Comment by abhijeetnishal** [comment]
Also refer the issue #70 for design.

**Comment by Isha1233** [comment]
@abhijeetnishal okhy

**Comment by Isha1233** [comment]
@abhijeetnishal I quit, there is problem in deployment of my push request in some of recent projects

**Comment by abhijeetnishal** [comment]
Ok @Isha1233, no issues.
