### ISSUE TITLE
Adding Signup And Login Page

### ISSUE THREAD

**Issue by kiruthigaa-k** [abhijeetnishal/URLShortener#168]
**Is your feature request related to a problem? Please describe.**
Adding the feature Signup And Login will make the websites looks more better.

**Describe the solution you'd like**
Adding the feature Signup And Login..

**Describe alternatives you've considered**

**Additional context**

**Comment by abhijeetnishal** [comment]
Hey @kiruthigaa-k, the login and signup pages will be added by issue #70 
Contribute to other issues, good luck.
