### ISSUE TITLE
QR Scanner Adding of  respective ShortURL  link ...

### ISSUE THREAD

**Issue by subhankarrout251** [abhijeetnishal/URLShortener#169]
**Is your feature request related to a problem? Please describe.**
Look When a person comes short the URL Because he/she wants to remember that there may be this QR code of that link Help out

**Describe the solution you'd like**
added also Download Option of that QR.
<img width="1056" alt="Screenshot 2024-06-10 at 6 24 45 PM" src="https://github.com/abhijeetnishal/URLShortener/assets/118932561/53831a34-104a-4acd-ba3d-8b78ff4109a3">

**Comment by TechSenseiX** [comment]
I am interested in resolving issue for GSSoC '24 and believe my skills in make me a good fit. Please assign it to me.
