### ISSUE TITLE
[Feature] Implement URL Save Functionality (Server side)

### ISSUE THREAD

**Issue by abhijeetnishal** [abhijeetnishal/URLShortener#17]
Followed by issue #16 

## Description:
The current URL Shortener project lacks a feature that allows authenticated users to save their shortened URLs. This will enable users to login and access their saved shortened URLs, along with their original URLs.

## Requirements:
- Shortened URL Save Functionality: Create an API endpoint (v1/api/urls) that allows authenticated users to save their shortened URLs with the original URL associated with the user_id on the server-side. 
- Database Integration: Integrate the shortened URL save functionality with our MongoDB database. Design a suitable schema to store the shortened URLs, original URLs, and user IDs.
- Get all shortened URL with original URL: Create a endpoint(v1/api/urls) that displays all shortened URLs saved by the user, along with their original URLs.
- Security: Ensure that the implementation follows best practices for security, including input validation, sanitization, and error handling.

## Acceptance Criteria:
- Authenticated users can save their shortened URLs on the server-side.
- The saved shortened URLs are associated with the user's ID in the database.
- The user home page displays all shortened URLs saved by the user, along with their original URLs.
- The implementation is secure, and input validation, sanitization, and error handling are in place.

### Estimated Time: 
This issue is estimated to take around 2-3 days to complete, depending on the contributor's experience.

**Comment by atharvarekhawar** [comment]
Hello @abhijeetnishal I would like to work on this issue, currently I see there is one more issue related to register/login assigned to someone else, so I will complete the above issue as soon as register/login implementation is completed as the userId is needed to complete the above functionality.

can you assign this issue to me.

**Comment by abhijeetnishal** [comment]
Great @atharvarekhawar, I think you understand the task. I am assigning this issue to you.
Best of luck.

**Comment by Ansh101112** [comment]
@abhijeetnishal i want to work on this issue also please assign me this issue to start working on it,

**Comment by abhijeetnishal** [comment]
Hey @atharvarekhawar, are you working on this issue or we will assign to @Ansh101112

**Comment by atharvarekhawar** [comment]
@abhijeetnishal I am working on this issue but I can't complete it without the Authentication part which is handled by someone else so I am unable to create PR.

I will still code it as much as possible till the other issue is solved.

**Comment by atharvarekhawar** [comment]
@abhijeetnishal I am unable to understand this requirement

Shortened URL Save Functionality: Create an API endpoint (v1/api/urls) that allows authenticated users to save their shortened URLs with the original URL associated with the user_id on the server-side.

we will save the URL as soon as it is created with the user_id then why the extra endpoint to save the URLs?

**Comment by abhijeetnishal** [comment]
Hey @atharvarekhawar, you just need to create an API which performs CRUD operation without update and it shows original URL with shortened url to respective users with JWT authentication which acts as a middleware.

Don't worry about the auth middleware for now. So i think it's level1 issue because CRUD and authentication are different issues.

If you have any doubts, let me know.

**Comment by prajna321** [comment]
@abhijeetnishal I'd love to take on this challenge. Please assign me this issue!

**Comment by atharvarekhawar** [comment]
@abhijeetnishal I will make a PR today itself , so plz keep the issue assigned to me

**Comment by abhijeetnishal** [comment]
> @abhijeetnishal I'd love to take on this challenge. Please assign me this issue!

Hey @prajna321, @atharvarekhawar is already working on this issue

**Comment by abhijeetnishal** [comment]
> @abhijeetnishal I will make a PR today itself , so plz keep the issue assigned to me

Hey @atharvarekhawar, don't worry about it.
I have merge the login/signup feature you can check I have to test it.

**Comment by abhijeetnishal** [comment]
Closing this issue as completed
