### ISSUE TITLE
Enhance Readme.md 

### ISSUE THREAD

**Issue by Aditijainnn** [abhijeetnishal/URLShortener#170]
Readme.md file is good currently but it can be more fascinating by adding animated emojis , fixing allignment , adding snapshots of our project, dsiplaying pfp of contributors in contri section and many more updates.

@abhijeetnishal please assign this issue to me I will update it
I am working under gssoc24

**Comment by abhijeetnishal** [comment]
Hey @Aditijainnn, there is no level for readme update a/c to gssoc guidelines. Are you still interested in this.

**Comment by Aditijainnn** [comment]
> Hey @Aditijainnn, there is no level for readme update a/c to gssoc guidelines. Are you still interested in this.

Their is level 1 but if there's not than nevermind i will still do it

**Comment by abhijeetnishal** [comment]
Ok @Aditijainnn, i am assigning this issue to you.

**Comment by Aditijainnn** [comment]
I have made changes you can review it.
