### ISSUE TITLE
History  feature for so  far  shortened urls

### ISSUE THREAD

**Issue by Mansi02-Sadanand** [abhijeetnishal/URLShortener#177]
addition of History feature for so  far  shortened urls for  a login user,

Users can easily retrieve previously shortened URLs without needing to remember or store them separately. This is particularly useful for recurring tasks or frequently shared links.

**Comment by abhijeetnishal** [comment]
Hey @Mansi02-Sadanand, there is an issue #98 for this. 

Closing this issue as duplicate.
