### ISSUE TITLE
[Bug] : Mismatch Text color

### ISSUE THREAD

**Issue by sivaprasath2004** [abhijeetnishal/URLShortener#178]
**Describe the bug**
- Aleting the `Copied` can't visible in the light mode.

**To Reproduce**
1. Go to  depoly page
2. Click on  `shorten it`
3. Click the `Copy` icon

**Screenshots**

[Screencast from 2024-06-14 20-39-14.webm](https://github.com/abhijeetnishal/URLShortener/assets/121082414/907d9230-6cfc-42d4-b0ca-12b3d413652b)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser : chrome

**Smartphone (please complete the following information):**
 - Device: Realme 8
 - OS:Android 12
 - Browser:chrome

**Comment by abhijeetnishal** [comment]
This will be fixed after ui-redesign branch. Contribute to other issues, good luck.
