### ISSUE TITLE
[Enhancement] Connect to Database only when required

### ISSUE THREAD

**Issue by abhijeetnishal** [abhijeetnishal/URLShortener#18]
## Description:
Currently, server establishes a connection to the MongoDB database as soon as the server starts. This means that the database connection is always active, even when no requests are being made to the server. This can lead to unnecessary resource usage and potential performance issues.

## Requirements:
- Modify the existing code to connect to the MongoDB database only when a request is received that requires database access.
- Ensure that the database connection is closed when it is no longer needed to conserve resources.
- Implement a mechanism to handle errors that may occur when connecting to the database lazily.
  
## Technical Details:
- Server is built using Node.js and Express.js as the backend framework.
- This project is using MongoDB as our database.
- The current implementation establishes a connection to the MongoDB database using the mongoose library in the server startup code.

## Example Scenario:
- When the server starts, no database connection is established.
- When a request is received to create a new shortened URL, the database connection is established, the URL is saved to the database, and the connection is closed.
- When a request is received to retrieve a shortened URL, the database connection is established, the URL is retrieved from the database, and the connection is closed.

### Acceptance Criteria:
- The database connection is not established when the server starts.
- The database connection is established only when a request is received that requires database access.
- The database connection is closed when it is no longer needed.
- Errors that occur during lazy loading of the database connection are handled correctly.

### Estimated Time: 
This issue is estimated to take around 1-2 days to complete, depending on the contributor's experience.

**Comment by Sarthak027** [comment]
Hey I want to work on this!! Can U assign this to me ??

**Comment by surendar-05** [comment]
Hey!! Assign this issue to me i want to work on this?

**Comment by abhijeetnishal** [comment]
Hey @surendar-05, This issue is already assigned to @Sarthak027. 
If the issue is not resolved then i will assign it to you.

Try to work on different issues, Good luck.

**Comment by shubhammjha22** [comment]
Could you please assign this issue to me? I'd like to work on implementing the changes using middleware and updating the existing code to connect to the MongoDB database lazily.

**Comment by abhijeetnishal** [comment]
> Could you please assign this issue to me? I'd like to work on implementing the changes using middleware and updating the existing code to connect to the MongoDB database lazily.

Hey @shubhammjha22, I already merged this issue. If you have any thoughts or idea to optimize this process let me know.
