### ISSUE TITLE
Adding a 404-Error Page

### ISSUE THREAD

**Issue by AkshitGarg24** [abhijeetnishal/URLShortener#182]
To ensure a positive user experience, a custom 404 error page should be created and displayed when a user navigates to a non-existent or incorrect web address. This page should provide a friendly message and useful navigation links.

**Comment by JaiBansal007** [comment]
I Want to Work on this project @abhijeetnishal  Could you Please Assign this task to me under GSSoC'24?

**Comment by abhijeetnishal** [comment]
Hey @AkshitGarg24 and @JaiBansal007, i guess 404 is there when some try to change url code. Contribute to other issues.
