### ISSUE TITLE
Hi @abhijeetnishal On submitting the shortening button -Green color hover effect should come as for good user experience!! please assign the issue under GSSOC'24

### ISSUE THREAD

**Issue by anmolraj-029** [abhijeetnishal/URLShortener#184]
Is your feature request related to a problem? Please describe.
I'm always frustrated when the form submission button does not provide immediate visual feedback during the submission process. This lack of feedback can leave users unsure whether their action was registered, leading to confusion or repeated clicks.

Describe the solution you'd like
I would like the submit button to display a green hover effect specifically when the form is in the submitting state. This will visually indicate to the user that their submission is being processed, providing a clear and immediate feedback that improves the overall user experience.

Describe alternatives you've considered
An alternative solution could be to change the button text or add a loading spinner next to the button text. However, these methods either do not provide a clear visual change (changing text) or might be too intrusive (spinner). A color change is subtle yet effective.

Additional context
Here's an example of the implementation in the button component:

**Comment by abhijeetnishal** [comment]
Hey @anmolraj-029, the complete UI will be changed as we have redesigned the UI. 

Contribute to other issues, good luck.
