### ISSUE TITLE
Fix: homepage screen height

### ISSUE THREAD

**Issue by Miran-Firdausi** [abhijeetnishal/URLShortener#185]
**Describe the bug**
On the homepage of the website, there is an unnecessary scrolling, even when the entire content can fit in without the need of scrollbar to appear.

**Expected behavior**
Adjust the height of main content to take full height while not exceeding 100vh.

Can you assign me under gssoc'24

**Comment by abhijeetnishal** [comment]
Hey @Miran-Firdausi, the UI is redesigned, so this will be fixed. Contribute to other issues good luck.
