### ISSUE TITLE
Adding hover effects on social media links 

### ISSUE THREAD

**Issue by Amruta7203** [abhijeetnishal/URLShortener#189]
**Is your feature request related to a problem? Please describe.**
Adding hover effect on social media links and aligning them in a line

![image](https://github.com/abhijeetnishal/URLShortener/assets/116087736/2d1a37fc-8362-4ee1-a43b-f25ee0761d7e)

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by abhijeetnishal** [comment]
Hey @Amruta7203, we don't need hover for now. Contribute to other issues, good luck.
