### ISSUE TITLE
[Bug] : `Copied` Text cannot Visible

### ISSUE THREAD

**Issue by sivaprasath2004** [abhijeetnishal/URLShortener#191]
**Describe the bug**
- `Copied` text cannot visible please check that. 
- assign me..

**To Reproduce**
1. Go to  `production page`
2. Click on  `copy Icon`
3. See error `Copied Text`

**Expected behavior**

**Screenshots** 

[Screencast from 2024-06-23 08-53-41.webm](https://github.com/abhijeetnishal/URLShortener/assets/121082414/9edba4d3-bb31-46a2-91ae-facff2004d9c)

**Desktop (please complete the following information):**
 - OS:Ubuntu
 - Browser : chrome 

**Smartphone (please complete the following information):**
 - Device: Realme
 - OS:  Android
 - Browser:chrome

**Comment by abhijeetnishal** [comment]
This is an issue #186 for this. Closing this as duplicate.
