### ISSUE TITLE
Feature Request: Add Footer to Website

### ISSUE THREAD

**Issue by HarshNA044** [abhijeetnishal/URLShortener#192]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I need to scroll back up to find important links or contact information. Having this information consistently available at the bottom of each page would improve the user experience significantly.

**Describe the solution you'd like**
I would like to have a footer added to the website that includes:
- Contact information (email, phone number)
- Social media links (Twitter, LinkedIn, GitHub, etc.)
- Copyright notice
- Quick links to important sections of the site (About, Blog, Contact, etc.)

**Describe alternatives you've considered**
As an alternative, I have considered adding these elements to a sidebar. However, a footer is more universally recognized and accessible, especially on mobile devices where sidebars can be less user-friendly.

**Comment by abhijeetnishal** [comment]
There is an issue #190 for this. Closing this issue as duplicate.
