### ISSUE TITLE
Adding some info and footer in the application

### ISSUE THREAD

**Issue by Akshitha-reddy-13** [abhijeetnishal/URLShortener#193]
Web application is too simple I can add some info and a footer also make it more attractive by changing UI
![image](https://github.com/abhijeetnishal/URLShortener/assets/122172211/35f3aa73-c7cc-4d12-9f69-096ef16edd34)
Can you assign it to me? @abhijeetnishal 

Full name: Akshitha Reddy
GitHub profile link: [Akshitha-reddy-13](https://github.com/Akshitha-reddy-13)
Email ID: akshithajagan13@gmail.com
What is your participant role?: GSSoC-2024 contributor

Can you add the label for GSSoC, please?
Thanks.

**Comment by abhijeetnishal** [comment]
Hey there is an issue #190 for this. Closing this issue as duplicate.
