### ISSUE TITLE
Add a sh script to locally install the application using a single command by running that file

### ISSUE THREAD

**Issue by Sahilll15** [abhijeetnishal/URLShortener#22]
As a contributor or user of the URL Shortener application, I often find the manual setup process time-consuming and prone to errors. To streamline the setup process and make it more accessible, I propose adding an automated setup script.

**Comment by Sahilll15** [comment]
assign this to me

**Comment by abhijeetnishal** [comment]
Great @Sahilll15, I am assigning this issue to you.
Good luck.

**Comment by Sahilll15** [comment]
add the level to the issue

**Comment by Sahilll15** [comment]
@abhijeetnishal bro add a level to this issue

**Comment by abhijeetnishal** [comment]
@Sahilll15 i already added labels enhancement and gssoc24
