### ISSUE TITLE
Improve the UI of the main page

### ISSUE THREAD

**Issue by bilalshaikh292** [abhijeetnishal/URLShortener#24]
**Is your feature request related to a problem? **
the UI is not very attractive and the yellow color text is not visible properly.

**Describe the solution you'd like**
I would like to change the font style and padding of some elements and the text color of some text.

**Comment by Pulkitxm** [comment]
Can I work on this?

**Comment by abhijeetnishal** [comment]
Hey @Pulkitxm, one issue #20 is already there for UI changes.
You can contribute to other issues or other projects.
