### ISSUE TITLE
Link Management

### ISSUE THREAD

**Issue by Sudhan22z265** [abhijeetnishal/URLShortener#27]
Users lack visibility and control over their previously shortened links, hindering their ability to track, manage, and analyze link performance effectively.

**Solution:**
Introduce a comprehensive link history feature that allows users to access and manage their previously shortened links. The implementation should include the following functionalities:

**Historical View:** Provide users with a chronological list of all links they have shortened, including details such as the original URL, shortened URL, creation date, and number of clicks.

### Please assign this to me. I am gssoc'24 contributor.

**Comment by Sudhan22z265** [comment]
please assign me this under gssoc'24

**Comment by abhijeetnishal** [comment]
Hey @Sudhan22z265, saving and showing all the shortened links issues are already exists, see #16 and #17.
Backend issue is already assigned and currently we are migrating from react to next.js #15 and after this we will work on frontend side.
