### ISSUE TITLE
[Enhancement] Add a feature display on the homepage

### ISSUE THREAD

**Issue by chaitanyarora** [abhijeetnishal/URLShortener#28]
![image](https://github.com/abhijeetnishal/URLShortener/assets/85432418/f86dd4a4-122b-4c1b-8a70-24c6b0c457d9)

Here's an example of what could be the design, later on we'll align with the website's design. @abhijeetnishal Sir can you please assign me this issue?

**Comment by abhijeetnishal** [comment]
Hey @chaitanyarora, I will assign this issue to you once i merge some important changes.

**Comment by chaitanyarora** [comment]
Is it okay if you can assign it to me? I'll start working on the feature only after you allow sir @abhijeetnishal .

**Comment by Sooraj002** [comment]
i would like to fix this issue

**Comment by abhijeetnishal** [comment]
Hey @chaitanyarora, I am assigning this issue to you now.
Remove Statistics and reliable feature from above UI and add User authentication and save urls feature as upcoming.
Use Tailwind CSS as we migrated code now.

**Comment by abhijeetnishal** [comment]
Hey @chaitanyarora, are you working on this issue?
What's the progress?

**Comment by chaitanyarora** [comment]
Yes sir

**Comment by chaitanyarora** [comment]
I'll link a PR by tomorrow

**Comment by abhijeetnishal** [comment]
> I'll link a PR by tomorrow

Great

**Comment by chaitanyarora** [comment]
@abhijeetnishal Sir is the frontend in React.js or Next.js?

**Comment by abhijeetnishal** [comment]
Hey @chaitanyarora, it's on nextjs we migrated. But it's doesn't matter it's almost same don't worry you need to add UI using Tailwind CSS.

**Comment by shreyansh1410** [comment]
Hi @abhijeetnishal can I contribute here?

**Comment by abhijeetnishal** [comment]
Hey @shreyansh1410, i think this issue #70 add this feature.

Closing this issue now.
