### ISSUE TITLE
Change the colour of loading

### ISSUE THREAD

**Issue by Rakshit-gen** [abhijeetnishal/URLShortener#29]
Changing the colour of loading as it is really similar to background and we can't know of it's there of not.

I am a Contributor for GSSoC 2024. Please assign this issue to me!

**Comment by Nehakumari1208** [comment]
I want to work on this project. please assign it to me

**Comment by abhijeetnishal** [comment]
Hey @Rakshit-gen and @Nehakumari1208, there is an issue regarding UI changes #20 
Please work on other issues for now. Good luck.
