### ISSUE TITLE
Clicking on the copy button doesn't notify the user

### ISSUE THREAD

**Issue by Judge-Paul** [abhijeetnishal/URLShortener#3]
After clicking the button to copy the new url nothing changes in the UI to notify me that the link has been copied.

**Comment by abhijeetnishal** [comment]
Hey @Judge-Paul, if you wanted to work on this issue go ahead, or I will fix that later. Thanks for noticing.

**Comment by Judge-Paul** [comment]
@abhijeetnishal Okay I'll work on it 
Also there is no padding on the actual input text unlike the placeholder text
![image](https://github.com/abhijeetnishal/URLShortener/assets/110723341/3c671d41-186d-4316-af2f-35053077defc)

**Comment by abhijeetnishal** [comment]
Hey @Judge-Paul, please try to fix whatever you think it's good for website.

**Comment by abhijeetnishal** [comment]
Fixed by PR #4
