### ISSUE TITLE
Implement url shortener as qr code (one of the feature)

### ISSUE THREAD

**Issue by Sudhan22z265** [abhijeetnishal/URLShortener#31]
**Problem:**
I'm always frustrated when I need to generate QR codes for shortened URLs separately, as it adds extra steps to the process and makes it less efficient.

**Solution:**
I would like the URL shortener to have built-in QR code generation functionality alongside shortened URLs. This would streamline the process and make it more convenient for users to create QR codes for their shortened links.

**Describe alternatives you've considered:**
One alternative could be using a separate QR code generation tool or service, but this would require users to switch between different platforms and may not integrate seamlessly with the URL shortener.

**Additional context:**
Implementing QR code generation directly within the URL shortener would enhance user experience and make the platform more comprehensive. It could be a valuable addition for users who frequently share links in offline settings or on physical materials.

### Please assign me this task i am gssoc'24 contributor @abhijeetnishal

**Comment by haard18** [comment]
I want to Work on this Issue under GSSOC'24

**Comment by abhijeetnishal** [comment]
Hey @Sudhan22z265, could you please explain the flow and UI how its look and little more details regarding this issue.
