### ISSUE TITLE
[BUG]: Missing Cursor Pointer

### ISSUE THREAD

**Issue by sivaprasath2004** [abhijeetnishal/URLShortener#37]
**Describe the bug**
The button element have no pointer during interaction.
**To Reproduce**
1. Go to  page
2. Click on the inspect
3. Scroll down to the button element

**Expected behavior**
- In mouse will be hover the mouse will be alerting to point.Doesn't  work it.

**Screenshots**
![Screenshot from 2024-05-11 13-08-56](https://github.com/abhijeetnishal/URLShortener/assets/121082414/b50c58a0-2490-45dc-a380-10ff64238631)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser : chrome

**Smartphone (please complete the following information):**
 - Device:Realme 8
 - OS: Android 12
 - Browser: chrome

**Comment by abhijeetnishal** [comment]
Hey @sivaprasath2004, there already exists an issue for UI refactoring #20. 
Work on the other issues good luck.

**Comment by sivaprasath2004** [comment]
@abhijeetnishal sorry I'll not notice that.

**Comment by abhijeetnishal** [comment]
> @abhijeetnishal sorry I'll not notice that.

No problem @sivaprasath2004
