### ISSUE TITLE
UI enhancement and navbar options

### ISSUE THREAD

**Issue by lovelyANSH2410** [abhijeetnishal/URLShortener#39]
First I will improve the UI by adding margin and padding also need to work on the font and icons, And i would also like to add some pages like contact us, about us for this app and apply navigation for those into the navbar also i can work for a good looking footer and favicon for this app.

**Comment by vinay02103** [comment]
hello Mentor,I'd want to contribute to this project as a GSsoc'24 contributor. Please give me this issue to work on.

**Comment by soham0005** [comment]
Hey @lovelyANSH2410, Can i work on this issue, also I have an idea implementing loader, what's say??

**Comment by abhijeetnishal** [comment]
one issue #20 is already there for UI changes.
Try to work on other issues.
I am closing this issue now as duplicate.
