### ISSUE TITLE
Feat: Copy to Clipboard feature

### ISSUE THREAD

**Issue by aryansharma220** [abhijeetnishal/URLShortener#43]
**Is your feature request related to a problem? Please describe.**
After getting the short link, there is no easy way to copy the link.

**Describe the solution you'd like**
We should add the option to copy the link to clipboard

**Additional context**
![image](https://github.com/abhijeetnishal/URLShortener/assets/133234867/dc387ffe-d8ed-47a0-9a6f-c18c8e43cc57)

@abhijeetnishal Please assign it to me under gssoc

**Comment by Nandini-49** [comment]
@abhijeetnishal Please assign it to me under gssoc

**Comment by kash2104** [comment]
@abhijeetnishal Can I work on this issue under GSSOC'24

**Comment by G0HAN3** [comment]
Hello @abhijeetnishal, could you please assign this issue to me? I believe my skills are well-suited to address it. Thank you!

**Comment by SatyajitPatra06** [comment]
Hey @abhijeetnishal , I've recently added a copy to clipboard feature to one of my projects (https://password-generator-nu-nine.vercel.app/), and hence I can do something similar to solve this issue, if assigned to me.

**Comment by prajna321** [comment]
I'd love to take on this task! Could you please assign this issue to me? Additionally, I kindly request adding the "GSSoC'24" label to this issue.
I have extensive experience in creating projects similar to this in the past. You can check out my GitHub profile (https://github.com/prajna321) here as proof of my experience.
Looking forward to contribute!

**Comment by abhijeetnishal** [comment]
Closing this issue as duplicate.
