### ISSUE TITLE
[Enhancement] Make UI Responsive for All Devices

### ISSUE THREAD

**Issue by abhijeetnishal** [abhijeetnishal/URLShortener#44]
## Description:
The current UI of our URL Shortener application is not fully responsive, resulting in a poor user experience on devices with different screen sizes and orientations. As a result, we need to ensure that our application's UI is adaptable and looks great on all devices, including desktops, laptops, tablets, and mobile phones.

## Requirements:

To achieve this, we need to make the following changes:
- Media Queries: Implement media queries using Tailwind CSS to define different styles for different screen sizes and orientations.
- Component Adjustments: Review and adjust individual components (e.g., buttons, forms, cards) to ensure they scale and adapt correctly on different devices.
- Typography: Ensure that typography is responsive, with font sizes and line heights adjusting according to screen size.
- Image Handling: Optimize image handling to ensure that images are displayed correctly and do not break the layout on different devices.

## Technical Details:
- Our application is built using Next.js with TypeScript.
- We are using Tailwind CSS for styling.

## Expected Outcome:
After completing this task, the URL Shortener application should have a fully responsive UI that adapts to different devices and screen sizes, providing an optimal user experience.

## Expected deadline:
It will take 1-2 days at max.

**Comment by gupta-ritik** [comment]
@abhijeetnishal assign this issues for resolve to me

**Comment by abhijeetnishal** [comment]
Great @gupta-ritik, I am assigning this issue to you now.

**Comment by gupta-ritik** [comment]
Thanks for assigning .

**Comment by Nehakumari1208** [comment]
Assign this to me

**Comment by abhijeetnishal** [comment]
> Assign this to me

Hey @Nehakumari1208, this issue is already assigned to @gupta-ritik. Work on other issues good luck.

**Comment by prajna321** [comment]
@abhijeetnishal  
Please assign me this issue! Would love to work on it.

**Comment by gupta-ritik** [comment]
@abhijeetnishal Hello Dear Sir
![WhatsApp Image 2024-05-13 at 23 16 23_26d4eb8c](https://github.com/abhijeetnishal/URLShortener/assets/127002992/70564e01-3420-4775-beaa-958d30d07b83)
, i facing a problem running server it showing some error.
I attached the error issue in the image and how to fix this issues please tell me

**Comment by abhijeetnishal** [comment]
> @abhijeetnishal Hello Dear Sir ![WhatsApp Image 2024-05-13 at 23 16 23_26d4eb8c](https://private-user-images.githubusercontent.com/127002992/330155580-70564e01-3420-4775-beaa-958d30d07b83.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2MjI4OTAsIm5iZiI6MTcxNTYyMjU5MCwicGF0aCI6Ii8xMjcwMDI5OTIvMzMwMTU1NTgwLTcwNTY0ZTAxLTM0MjAtNDc3NS1iZWFhLTk1OGQzMGQwN2I4My5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxM1QxNzQ5NTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMWRmMWJmYWI3Mzk5ODUxODNjNTdiM2I4YzlmNjczYzJkYTJiZTBhMWFiZGJlOTk3ZWFhYWY5NDMxNmU3MDRjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.VU3Nt-xI_RxxgF2iO8OlbuJUwcEbVAz2JprqWh0wrhY) , i facing a problem running server it showing some error. I attached the error issue in the image and how to fix this issues please tell me

Hey @gupta-ritik, for running client run: npm i command in client director. 

If you are getting error then remove node_modules and .next folder and then run npm i command.

**Comment by abhijeetnishal** [comment]
Hey @gupta-ritik, what's the progress, are you working on this?

**Comment by gupta-ritik** [comment]
i still facing above mentioned issues

**Comment by abhijeetnishal** [comment]
Try to clone the project again and install and run it will run else I think it will system level issue.

Try to debug this issue

**Comment by hrishabhpatel09** [comment]
sure @abhijeetnishal  i would love to contribute on this issue.
