### ISSUE TITLE
[Feature] Implement Login and Signup for Client-Side

### ISSUE THREAD

**Issue by abhijeetnishal** [abhijeetnishal/URLShortener#45]
## Description:
We need to implement a responsive and visually appealing login and signup page for the client-side of our URL Shortener application. The page should be designed with a focus on user experience and should be fully functional, allowing users to successfully log in and sign up for an account.

## Requirements:
- The login and signup pages should be built using Next.js with TypeScript.
- The design should be responsive, meaning it should adapt to different screen sizes and devices (desktop, tablet, mobile).
- The pages should be styled using Tailwind CSS.
- The login page should include the following fields:
  - Username or email address
  - Password
  - Login button
- The signup page should include the following fields:
  - name
  - email address
  - Password
  - Confirm password
  - Signup button
- Both pages should include error handling and validation for the input fields.
- The pages should be accessible and follow best practices for web accessibility.
- The design should be consistent with the overall aesthetic of the application.

## Functional Requirements:
- The login page should authenticate users and redirect them to the dashboard or main application page upon successful login.
- The signup page should create a new user account and redirect them to the dashboard or main application.
- Both pages should handle errors and exceptions gracefully, providing user-friendly error messages.

## Acceptance Criteria:
- The login and signup pages are fully functional and responsive.
- The design is consistent with the overall aesthetic of the application.
- The implementation meets the technical requirements and follows best practices.
- The code is well-organized, modular, and easy to maintain.

**Comment by rahul-2004-json** [comment]
@abhijeetnishal  plz assign this feature to me under GSSOC'24. I am really eager to contribute to this project

**Comment by abhijeetnishal** [comment]
Hey @rahul-2004-json, share the UI you are planning to use for login/signup according to this project. 
Assigning this issue to you now.

**Comment by rahul-2004-json** [comment]
@abhijeetnishal  thank you for assigning me this issue. I will do my best to complete the task

**Comment by abhijeetnishal** [comment]
Hey @rahul-2004-json, please share design/UI you are referencing before implementing so that we can verify design/UI looks good to this project or not.

**Comment by rahul-2004-json** [comment]
![12](https://github.com/abhijeetnishal/URLShortener/assets/74658609/39d2acbf-1482-425a-83bf-79a74a44aabf)
I will try to implement like this with form validation and mongodb connection also ... if there will be a need for different ui i will definatley change it

**Comment by abhijeetnishal** [comment]
![Screenshot 2024-05-12 171103](https://github.com/abhijeetnishal/URLShortener/assets/83833440/6024e747-1e65-4ab3-88da-ba859537d7a9)

Hey @rahul-2004-json, use this UI for login/register page. This UI is official tailwind site: https://tailwindui.com/components/application-ui/forms/sign-in-forms

Hey login and signup API endpoint is in progress #16 so don't need to worry about server focus on client side.

**Comment by rahul-2004-json** [comment]
Ok I will do it this way !!

**Comment by Manaswini123456** [comment]
@abhijeetnishal Kindly assign me with this issue, as I have worked with similar type in the past. I would like to provide my insights and solutions.

**Comment by prajna321** [comment]
@abhijeetnishal 
I'd love to work on it . Please assign me this issue!

**Comment by abhijeetnishal** [comment]
Hey @Manaswini123456, the issue is already assigned to @rahul-2004-json. Work on other issues or project, good luck

**Comment by Manaswini123456** [comment]
@abhijeetnishal will look into it. Thanks!
