### ISSUE TITLE
Hovering effect on shorten it button 

### ISSUE THREAD

**Issue by Nehakumari1208** [abhijeetnishal/URLShortener#48]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Nehakumari1208** [comment]
Assign me this issue i will fix it

**Comment by abhijeetnishal** [comment]
Hey @Nehakumari1208, one issue regarding UI changes already exists #20 
Work on other issues l, good luck 
Closing this issue now as duplicate.
