### ISSUE TITLE
[Enhancement] Redesign UI of Home page 

### ISSUE THREAD

**Issue by sammy429b** [abhijeetnishal/URLShortener#50]
**Description:**

The current home screen lacks clarity and organization, making it challenging for users to access important features easily, such as logging in or navigating to different sections. To address this issue, the proposed solution involves redesigning the home page with a clear navbar at the top, containing buttons for logging in and logging out. Additionally, a sidebar will be added to provide easy access to different sections. The sidebar will include a "Home" section for navigating back to the main page and a "Links" section for accessing the history of shortened links. This UI update aims to enhance the user experience by improving navigation and providing clear access to essential features.

**Requirements:**

1. Clear navbar at the top of the home page.
2. Navbar must contain buttons for logging in and logging out.
3. Addition of a sidebar for easy access to different sections.
4. Sidebar should include a "Home" section and a "Links" section.
5. The "Home" section should allow users to navigate back to the main page.
6. The "Links" section should provide access to the history of shortened links.

**Acceptance Criteria:**

1. Users can easily locate the navbar at the top of the home page.
2. Navbar buttons for logging in and logging out are clearly visible and functional.
3. The sidebar is present on the home page and accessible from any screen within the application.
4. The "Home" section in the sidebar allows users to navigate back to the main page without any issues.
5. The "Links" section in the sidebar displays the history of shortened links accurately.
6. Usability testing confirms that users find the new layout intuitive and navigation is significantly improved compared to the previous design.

**Comment by prajna321** [comment]
I'd love to work on this. Please assign me this issue! @abhijeetnishal

**Comment by abhijeetnishal** [comment]
Currently we don't want to redesign our homepage.
