### ISSUE TITLE
[Bug] The shorten it button is not properly aligned in mobile devices 

### ISSUE THREAD

**Issue by fazil-syed** [abhijeetnishal/URLShortener#53]
**Describe the bug**
The shorten it button is not aligned properly in mobile devices 
**To Reproduce**
1. Go to https://urlsrtner.vercel.app/
2. On a mobile device
3. See the shorten it button 

**Expected behavior**
It should be properly aligned with some space on the left
**Screenshots**
![Screenshot_2024-05-12-16-11-46-478_com brave browser](https://github.com/abhijeetnishal/URLShortener/assets/84120587/46ad04df-9bd6-47e1-9077-874ae3ec2f37)

**Smartphone (please complete the following information):**
 - Device: [POCO M4]
 - OS: [Android 13]
 - Browser [Brave]

**Comment by abhijeetnishal** [comment]
Hey @fazil-syed, one issue is already there for responsive design #44
Work on other issues or repos, good luck.
Closing this issue as duplicate.
