### ISSUE TITLE
[Feature] Toggle for dark or light mode

### ISSUE THREAD

**Issue by Utkarsh-Pandey-GitHub** [abhijeetnishal/URLShortener#54]
i want to add dark mode to the website.

**Comment by SatyajitPatra06** [comment]
The page is already dark!

**Comment by SanaAzeem512** [comment]
@Utkarsh-Pandey-GitHub please assign this issue to me under gssoc24

**Comment by SatyajitPatra06** [comment]
the website already responds to system dark mode, still I can add a manual dark mode toggle button, if assigned to me @abhijeetnishal

**Comment by abhijeetnishal** [comment]
Hey @Utkarsh-Pandey-GitHub and @SanaAzeem512, the UI is adaptable for dark mode.

**Comment by abhijeetnishal** [comment]
Hey @SatyajitPatra06, I am assigning this issue to you.

Things to remember:
1. Don't use any external package or library for this 
2. Code should be written in such a way that it should work for every screen in later stages if we add pages later.
3. Use Tailwind CSS

**Comment by abhijeetnishal** [comment]
Hey @SatyajitPatra06, what's the progress?
Are you still working on this issue

**Comment by Prashant-2024** [comment]
Hi, 
Myself Prashant, I would like to work on this under GSSOC'24.
Please assign it to me.

**Comment by abhijeetnishal** [comment]
Hey @Prashant-2024, assigning this issue to you.

**Comment by Prashant-2024** [comment]
Update:
Almost Done with the Feature

**Comment by abhijeetnishal** [comment]
Hey @Prashant-2024, any update? 
If you need any help let me know

**Comment by Prashant-2024** [comment]
Just having some render issue, I will be solving it ASAP. 
I have End sem exam tomorrow, leading to delay for PR. 
But I will try to raise PR by today itself.

**Comment by abhijeetnishal** [comment]
> Just having some render issue, I will be solving it ASAP. I have End sem exam tomorrow, leading to delay for PR. But I will try to raise PR by today itself.

Ok no issues, focus on your exam today leave it

**Comment by Madhuril-Bhaskar** [comment]
PLEASE ASSIGN IT TO ME

**Comment by abhijeetnishal** [comment]
Hey @Madhuril-Bhaskar,  i guess @Prashant-2024 is working on this issue.
Contribute to other issues or projects good luck

**Comment by abhijeetnishal** [comment]
Hey @Prashant-2024, are you working on this issue there is limit of 4-5 days for issue under gssoc also this feature is needed for this project, we can't delay. Let me know if you on it else i will assign to @Madhuril-Bhaskar

**Comment by Prashant-2024** [comment]
yes, I am working on it.
I will raise the PR within 1 hour

**Comment by singhJasvinder101** [comment]
Hey @abhijeetnishal I would like to work on this issue.

**Comment by abhijeetnishal** [comment]
Closing this issue as done
