### ISSUE TITLE
Shorten it button misalignment 

### ISSUE THREAD

**Issue by SalehaTabassum** [abhijeetnishal/URLShortener#56]
![Screenshot_2024-05-12-18-45-52-88_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/abhijeetnishal/URLShortener/assets/169278740/7e4b3a14-a86b-471a-a144-fc316c728649)
 As we can see here shorten it button is not properly aligned.It should be in the center and it should be a little bit lower as it's touching 
The previous input field.

Please assign this issue to me under GSSOC 2024 and add necessary labels to it
@abhijeetnishal

**Comment by hrishabhpatel09** [comment]
I want to work on this issue. Could You please assign me this

**Comment by hrishabhpatel09** [comment]
I want to work on this issue could you please assign @abhijeetnishal

**Comment by abhijeetnishal** [comment]
Hey there is an issue #44 which solves this.
Closing this issue as duplicate.
