### ISSUE TITLE
Validate the url first then short the url

### ISSUE THREAD

**Issue by RoshanAnsy** [abhijeetnishal/URLShortener#58]
**Describe the bug**
It does not verify whether the URL entered by the user is valid or not

**Screenshots**

![Screenshot 2024-05-12 194634](https://github.com/abhijeetnishal/URLShortener/assets/91673102/b8f7fa2f-f05f-4819-8d05-f79d0d88f8bd)

**Comment by RoshanAnsy** [comment]
valid-url module desc ..............

![Screenshot 2024-05-12 195559](https://github.com/abhijeetnishal/URLShortener/assets/91673102/87545d07-7bb6-4aba-8d50-ab7fd9dbbe29)

**Comment by RoshanAnsy** [comment]
add the gssoc  tag as well as level.

**Comment by RoshanAnsy** [comment]
We need to discuss this issue because we require more servers for these validations, or explore alternative methods. First, we should discuss which method is best for this project.

Let's set up a meeting for it.

**Comment by abhijeetnishal** [comment]
Hey @RoshanAnsy, we will discuss regarding this issue on discord in a day or two once mentor and project channel is created.

**Comment by DevPatel1023** [comment]
Hey @abhijeetnishal can you please share the discord channel link i am intersted in this project to contributing.

**Comment by abhijeetnishal** [comment]
> Hey @abhijeetnishal can you please share the discord channel link i am intersted in this project to contributing.

Hey @DevPatel1023, currently it is not active as gssoc setting up things.

**Comment by abhijeetnishal** [comment]
Merged by #88
