### ISSUE TITLE
Website logo on the header of the web site

### ISSUE THREAD

**Issue by RamakrushnaBiswal** [abhijeetnishal/URLShortener#59]
**Is your feature request related to a problem? Please describe.**
Website logo on the header of the web site

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
![image](https://github.com/abhijeetnishal/URLShortener/assets/125277258/70ba989e-0f8b-4f19-aaf0-72f8b31b4368)

**Comment by abhijeetnishal** [comment]
Hey @RamakrushnaBiswal, Assigning this issue to you now.

**Comment by abhijeetnishal** [comment]
Hey @RamakrushnaBiswal, are you done with this issue i guess it will not take that much time
