### ISSUE TITLE
Copy Button Feature

### ISSUE THREAD

**Issue by lakshyajn** [abhijeetnishal/URLShortener#61]
**Is your feature request related to a problem? Please describe.**
Most people know to copy it from right click, but it is very frustrating to do right-click and finding the "copy-link address" option.

**Describe the solution you'd like**
It would be nice to have a copy button and users are able to have link to their shortened link in their clipboard.
Also designing button matching with other UI components would also affect UX positively.

**Describe alternatives you've considered**
Alternative would be like instead of introducing the button, we add symbol just right to the shorten url button,
Else all would be same.

@abhijeetnishal Please assign this Issue to Me :)

**Comment by prajna321** [comment]
@abhijeetnishal I have experience working on similar issues in the past and would love to tackle this one. Could you please assign it to me?

**Comment by abhijeetnishal** [comment]
Hey @lakshyajn and @prajna321 do you have any UI reference how the copy button looks, please share i will assign this issue

**Comment by prajna321** [comment]
@abhijeetnishal somewhat like the attached picture. 
![IMG_20240515_002445](https://github.com/abhijeetnishal/URLShortener/assets/121210533/28e59ee0-edc9-446f-a9eb-89f365463fe5)

**Comment by abhijeetnishal** [comment]
Ok great @prajna321, assigning this issue to you now.
Use Tailwind CSS and don't use external package and UI should be responsive.

**Comment by hrishabhpatel09** [comment]
Could you please assign me i can do that @abhijeetnishal

**Comment by abhijeetnishal** [comment]
Hey @hrishabhpatel09, this issue is already assigned to @prajna321 as fcfs order.
You can contribute to other issues, good luck

**Comment by mtg718** [comment]
Hi @hrishabhpatel09 , please assign this issue to me under GSSoc'24

**Comment by abhijeetnishal** [comment]
Closing this issue as completed.
