### ISSUE TITLE
Adding a feature to store Urls entered by users

### ISSUE THREAD

**Issue by Rohitha-pudu** [abhijeetnishal/URLShortener#63]
### storing the urls 
I will work on this issue.i will implement it using mongodb.please assign this to me

**Comment by prajna321** [comment]
@abhijeetnishal I have experience working on similar issues in the past and would love to tackle this one. Could you please assign it to me?

**Comment by abhijeetnishal** [comment]
Hey this issue is already there, work on other issues.
I am closing this issue as duplicate.
