### ISSUE TITLE
Using Python API to get Shortend URL 

### ISSUE THREAD

**Issue by binguliki** [abhijeetnishal/URLShortener#67]
**Is your feature request related to a problem? Please describe.**
I didnt find any appropriate code for generating a shortend URL in your database

**Describe the solution you'd like**
I would be provide a python script that uses an API that takes a Valid URL as an Input and returns a shortend URL

**Additional context**
@abhijeetnishal Hey 👋 Can you please assign this task to me under GSSoC 24 with an appropriate level tag i would love to work on it , I'm a python Developer and I know how to solve this problem , Also if you need any extra changes I would be adding that too

**Comment by abhijeetnishal** [comment]
There is already an issue #58 
Closing this issue as duplicate.
