### ISSUE TITLE
feat: share shorten url to whatsapp without copying it

### ISSUE THREAD

**Issue by himanshugoyal77** [abhijeetnishal/URLShortener#74]
**Is your feature request related to a problem? Please describe.**
want to add feature which automatically shares shorten link to whatsapp and gmail without copying

**Describe the solution you'd like**
I will add two Icons i.e. whatsApp logo and gmail logo
and by clicking them users can directly share the shorten url with others

**Comment by rahul1841** [comment]
I would like to work on this project. 
i will add feature of direct sharing on whatsapp, gmail and linkedin without need to copy .
Please assign it to me

**Comment by himanshugoyal77** [comment]
@rahul1841 I have raised this issue and I want to solve it.

**Comment by himanshugoyal77** [comment]
@abhijeetnishal please take a look.

**Comment by abhijeetnishal** [comment]
Hey @rahul1841, how do you planning to solve this issue. This is valid to only whatsapp our social media too, you are using any external package, etc

**Comment by rahul1841** [comment]
Hey @abhijeetnishal  :  WhatsApp has a predefined URL format for sharing messages, then we can take shorturl generate and embed the shortened URL into this template and then we can create a whatsapp icon in frontend by clicking on which user can share url directly on whatapp.
we can do this same for linkedin and gmail also.

**Comment by rahul1841** [comment]
@abhijeetnishal  please assign it to me

**Comment by abhijeetnishal** [comment]
> @abhijeetnishal please assign it to me

Assigning this issue to you @rahul1841

**Comment by abhijeetnishal** [comment]
Don't use external package for this try to do it using custom methods.

**Comment by rahul1841** [comment]
@abhijeetnishal  from the day i have been assign issue , your website is not working properly as it do not giving short urls so i was not able to procced next , now it is working so i start working on it , till tomorrow i will complete it

**Comment by rahul1841** [comment]
@abhijeetnishal i have made pull request and added functionality you have assigned to me, please review it and merge it

**Comment by abhijeetnishal** [comment]
Closing this issue as done.
