### ISSUE TITLE
[FEAT] : Add QR Code Feature 

### ISSUE THREAD

**Issue by Harshit7492** [abhijeetnishal/URLShortener#78]
# Description
- The QR Functionality is still a new feature which is not added in it.
- Create QR Code for the given link helps other users 

# What this featue do
- This solution generates a QR code for a given link, facilitating easy access to the associated web content through scanning.

# Screenshots
![Screenshot 2024-05-15 083204](https://github.com/abhijeetnishal/URLShortener/assets/114082380/2ab58104-463b-43ac-a2c5-5ac13a6dcc36)

# Additional Screenshots
- Add any other context or screenshots about the feature request here to show how this feature look like a small example...
![Screenshot 2024-05-15 083820](https://github.com/abhijeetnishal/URLShortener/assets/114082380/62f04bf7-4c54-46ac-a8d3-e79868c9961b)

**Comment by Harshit7492** [comment]
I @Harshit7492 want to fix this feature and request to @abhijeetnishal to assign me 
Thank you

**Comment by abhijeetnishal** [comment]
Hey @Harshit7492, there is an issue #32 
Work on other issues good luck
