### ISSUE TITLE
[Feat] create User Url History Page 

### ISSUE THREAD

**Issue by CoderSwarup** [abhijeetnishal/URLShortener#79]
**Is your feature request related to a problem? Please describe.**
This feature aims to enhance user experience by displaying the history of URLs shortened by the user. It will enable users to easily access their previously shortened URLs and provide analytics through charts, showing the number of clicks each URL has received and the frequency of URL visits over time.

**Describe the solution you'd like**
Implement a user-friendly history page that lists all the URLs a user has shortened. Each entry should include:

-The original URL
-The shortened URL
-The number of clicks
-Date created
-Additionally, integrate visual charts to present analytics

**Describe alternatives you've considered**

**Additional context**
This feature will significantly improve user engagement and retention by offering valuable insights and easy access to their URL data. Below are some mockups and references to similar features in other URL shortener services to illustrate the proposed implementation.

please assign me this issue i want to work on this issue

**Comment by abhijeetnishal** [comment]
Hey @CoderSwarup, currently login signup flow not completed #45 
Work on other issues or projects, good luck.
