### ISSUE TITLE
Add FAQ Section to the website

### ISSUE THREAD

**Issue by MastanSayyad** [abhijeetnishal/URLShortener#82]
Hi @abhijeetnishal ,
A dedicated FAQ section within the website, provides clear and concise answers to the common questions related to the platform.

For example:

![image](https://github.com/abhijeetnishal/URLShortener/assets/101971980/c9088f17-6774-4fbb-923c-f7eb8fcecce6)

Could you **please assign this issue to me under GSSoC 24**?

**Comment by abhijeetnishal** [comment]
There is an issue #28 related to this.
Closing this issue as duplicate.
