### ISSUE TITLE
[Enhancement] Add zod schema validation for urls and email

### ISSUE THREAD

**Issue by frumptiousclone** [abhijeetnishal/URLShortener#86]
Title: Implement Zod Validation for URL and Email Inputs

**Description**:
I propose adding Zod validation for URLs and email inputs in the URL shortener project to ensure that the data entered by users is in the correct format, reducing errors and improving the overall reliability of the application.

**Rationale**:
- URL Validation: Zod validation will ensure that URLs entered by users are valid and properly formatted, preventing issues such as broken links.
- Email Validation: Validating email inputs will ensure that the emails provided by users are in the correct format, reducing errors in communication.

**Proposed Solution:**
- Implement Zod validation for URLs and email inputs using the Zod library in the frontend and/or backend of the application.
- Display appropriate error messages if the input does not match the required format, guiding users to enter valid data.

This enhancement will improve the user experience by providing immediate feedback on the validity of URLs and email inputs, reducing the likelihood of errors. I am willing to contribute to the implementation of this feature and would appreciate any guidance or feedback on how to best proceed.

**Request:**
Please label this issue as a GSSOC (GirlScript Summer of Code) issue and assign it to me for implementation.

Thank you for considering this enhancement.

**Comment by Debajyoti045** [comment]
can you please assign this issue to me @abhijeetnishal 
I know the zod schema well

**Comment by abhijeetnishal** [comment]
Hey @Debajyoti045, we don't need any external package for input validation it is done using JS function/methods only.

You can contribute to other issues, good luck.

**Comment by frumptiousclone** [comment]
Hey @abhijeetnishal, thanks for responding. I checked the urls.js file and found the js function for url validation. I agree that zod is not needed there, sorry for not noticing that earlier but don't you think validating the email input before signing up a new user will be better? I think it will save a db call and more importantly it will prevent the storage of invalid emails. 
This code here checks if the user has entered email, password and name but does not validate whether or not it is a valid email.
If you don't want to use any external package then I can use regular expressions for email validation as well. Please tell me your thoughts. Thank you.

**Comment by abhijeetnishal** [comment]
> Hey @abhijeetnishal, thanks for responding. I checked the urls.js file and found the js function for url validation. I agree that zod is not needed there, sorry for not noticing that earlier but don't you think validating the email input before signing up a new user will be better? I think it will save a db call and more importantly it will prevent the storage of invalid emails. This code here checks if the user has entered email, password and name but does not validate whether or not it is a valid email. ![Screenshot 2024-05-16 123646](https://private-user-images.githubusercontent.com/135329687/331090415-fb47581f-bec0-43be-b45c-36b7a43e3506.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU4NDQ4MTgsIm5iZiI6MTcxNTg0NDUxOCwicGF0aCI6Ii8xMzUzMjk2ODcvMzMxMDkwNDE1LWZiNDc1ODFmLWJlYzAtNDNiZS1iNDVjLTM2YjdhNDNlMzUwNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxNlQwNzI4MzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MGI3NGRjNjZjMzkzZTBmOTcxMjQ5NjljMzc3MGM3MzNjMzAyNmVhNTVmOTBiOGMyN2E4MWVlMGI1YzRmM2JiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.3O5kH-mueiHryQ1fqOyjIL4Bx8p_YTvWDK-kurna0VY)
> 
> If you don't want to use any external package then I can use regular expressions for email validation as well. Please tell me your thoughts. Thank you.

Hey @frumptiousclone, we can handle that from client side, later we will see.
