### ISSUE TITLE
[Feature] : Display shortened link in a new div and a button to copy it.

### ISSUE THREAD

**Issue by Shelbybosss** [abhijeetnishal/URLShortener#91]
Display shortened link in a new div and a button to copy it.

**Comment by Shelbybosss** [comment]
@RamakrushnaBiswal Assign me development of this feature

**Comment by abhijeetnishal** [comment]
This feature is already there sometimes its not visible in light mode
Work on other issues or project, good luck.

**Comment by Shelbybosss** [comment]
lol, not visible to me still and is there even a button to switch between dark mode and light mode i dont see it, anyways not interested to commit to this rep anymore good luck with your newbie college proj.

**Comment by abhijeetnishal** [comment]
There is an issue for light/dark toggle #54

**Comment by abhijeetnishal** [comment]
> lol, not visible to me still and is there even a button to switch between dark mode and light mode i dont see it, anyways not interested to commit to this rep anymore good luck with your newbie college proj.

Great 👍 good luck
