### ISSUE TITLE
Google Signup

### ISSUE THREAD

**Issue by pragati-himadri** [abhijeetnishal/URLShortener#93]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by pragati-himadri** [comment]
The sign-up process will be faster as users do not need to fill out lengthy registration forms; their Google account information is used to populate the necessary fields.Please assign me this issue under GSSOC'24!!

**Comment by abhijeetnishal** [comment]
Hey @pragati-himadri, currently email login signup is still remaining to implement #45 
Work on other issues or projects, good luck.
