### ISSUE TITLE
Integrate React-Toastify for Premium Notifications

### ISSUE THREAD

**Issue by Vikranthraosb** [abhijeetnishal/URLShortener#95]
Add React-Toastify to project for enhanced notifications.
Configure toast notifications for various events (e.g., success, error, info).

something like this :-
![Screenshot (235)](https://github.com/abhijeetnishal/URLShortener/assets/102306707/66782827-9432-4235-8db8-7f6c3767a94c)

**Comment by abhijeetnishal** [comment]
We already have react-toast feature
Work on other issues or project, good luck.
