### ISSUE TITLE
Feat:[Backend] Login & Signup.

### ISSUE THREAD

**Issue by abhiperfect** [abhijeetnishal/URLShortener#97]
**Is your feature request related to a problem? Please describe.**
I am facing difficulties with the current authentication system, as it lacks proper login and signup functionality. 

**Describe the solution you'd like**
I would like to implement a robust login and signup system in the backend to improve user authentication and security.

**Describe alternatives you've considered**
One alternative solution could be to patch the existing authentication system, but I believe building a dedicated login and signup feature would provide a more reliable and scalable solution.

**Additional context**
No additional context at the moment.

**Comment by abhiperfect** [comment]
I would like work on this issue.

**Comment by abhijeetnishal** [comment]
Hey @abhiperfect, login/signup is already implemented and merged for backend.
Closing this as already done.
