### ISSUE TITLE
Feat: Storing all URLs. 

### ISSUE THREAD

**Issue by abhiperfect** [abhijeetnishal/URLShortener#98]
**Is your feature request related to a problem? Please describe.**
Currently, users do not have visibility into the shortened URLs they have created after logging into their profiles.

**Describe the solution you'd like**
I would like to implement a feature where users can view all the shortened URLs associated with their account after logging in. This would provide users with better visibility and control over their shortened URLs.

**Describe alternatives you've considered**
An alternative solution could be to allow users to access their shortened URLs through a unique link sent to their email after each URL is shortened. However, this approach may be less convenient for users and could lead to cluttered inboxes.

**Additional context**
Having the ability to view all shortened URLs in their profile would enhance the user experience and improve the usability of the URL shortening service.

**Comment by abhiperfect** [comment]
I would like to work on this issue.

**Comment by abhijeetnishal** [comment]
Hey @abhiperfect, currently login/signup and authentication done then we will work on this

**Comment by abhiperfect** [comment]
> Hey @abhiperfect, currently login/signup and authentication done then we will work on this

Ok @abhijeetnishal , could you please assign me this task after login/signup completion.

**Comment by abhijeetnishal** [comment]
I will let you know

**Comment by Aditya2ReaLNITKKR** [comment]
@abhijeetnishal  can you assign me this task under ggsoc'24

**Comment by Aditya2ReaLNITKKR** [comment]
@abhijeetnishal  can you tell where we will be storing history on server ? or in cookies ?. 
form my point of view , server side saving is good. it will persist even if user clear cookies or history in browser.

**Comment by abhijeetnishal** [comment]
Hey @Aditya2ReaLNITKKR, we can use server side approach not cookies as i explained in #106

**Comment by riyasaxena32** [comment]
I am interested in resolving issue for GSSoC '24 and believe my skills in make me a good fit. Please assign it to me.

**Comment by abhijeetnishal** [comment]
Hey @riyasaxena32, there are some issues like #70 that needs to be done before this. Also @abhiperfect asked this issue to assign.

**Comment by abhijeetnishal** [comment]
Hey @abhiperfect, do you have any designs for this feature?

**Comment by abhijeetnishal** [comment]
Closing this issue as not active.
