### ISSUE TITLE
Feat: Copy Icon.

### ISSUE THREAD

**Issue by abhiperfect** [abhijeetnishal/URLShortener#99]
**Is your feature request related to a problem? Please describe.**
Currently, users may find it inconvenient to manually copy shortened URLs after they are generated.

**Describe the solution you'd like**
I would like to see a copy icon placed next to the "Shorten" button, allowing users to easily copy the shortened URL with a single click.

**Describe alternatives you've considered**
An alternative solution could be to provide a "Copy" button next to the shortened URL, but having a copy icon directly next to the "Shorten" button may offer a more intuitive and streamlined user experience.

**Additional context**
Implementing this feature would enhance user convenience and efficiency when using the URL shortening service.

**Comment by abhiperfect** [comment]
I would like to work on this issue.

**Comment by hrishabhpatel09** [comment]
Already solved. merged in #87
